#pragma config(Motor,  port3,           leftwheel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rightwheel,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           test1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           test2,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[port7] = vexRT[Ch2];
		motor[port6] = vexRT[Ch3];

		if(vexRT[Btn5U]){
			motor[port3] = -127;
		} else if (vexRT[Btn5D]) {
			motor[port3] = 127;
		} else {
			motor[port3] = 0;
		}

		if(vexRT[Btn6U]){
			motor[port4] = -127;
		} else if (vexRT[Btn6D]) {
			motor[port4] = 127;
		} else {
			motor[port4] = 0;
		}

		//Evan's Redesign
		/*if(vexRT[Btn5U] == 1)
		{  motor[port3] = 255;
				motor[port4] = -255;
	  } else if(vexRT[Btn6U]){
	 			motor[port3] = -255;
	 			motor[port4] = 255;
	}*/
 }
}
