#pragma config(Motor,  port3,           leftwheel,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           rightwheel,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port5,           rotatingbase,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           arm,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[port3] = vexRT[Ch3];
		motor[port4] = vexRT[Ch2];
		//Evan's Redesign
		/*if(vexRT[Btn5U] == 1)
		{  motor[port3] = 255;
				motor[port4] = -255;
	  } else if(vexRT[Btn6U]){
	 			motor[port3] = -255;
	 			motor[port4] = 255;
	}*/
 }
}


